# Generated by Django 2.2 on 2019-04-26 15:52

from django.db import migrations, models
import findance.abstract
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', findance.abstract.FindanceIdField(default=findance.abstract.FindanceIdField._build_id, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('fullname', models.TextField()),
                ('rate', findance.abstract.MonetaryField(decimal_places=10, default=1.0, max_digits=64)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCurrency',
            fields=[
                ('id', findance.abstract.FindanceIdField(db_index=True, default=findance.abstract.FindanceIdField._build_id)),
                ('code', models.TextField(db_index=True)),
                ('fullname', models.TextField()),
                ('rate', findance.abstract.MonetaryField(decimal_places=10, default=1.0, max_digits=64)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical currency',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
