# Generated by Django 2.2 on 2019-04-26 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def _build_usd(apps, schema_editor):
    """ Create the base USD object """
    Currency = apps.get_model("currency", "Currency")
    db_alias = schema_editor.connection.alias
    Currency.objects.using(db_alias).get_or_create(
        code='USD',
        fullname='United States Dollar',
        rate=1.0
    )

def _destroy_usd(apps, schema_editor):
    """ Remove the USD object """
    Currency = apps.get_model("currency", "Currency")
    db_alias = schema_editor.connection.alias
    Currency.objects.using(db_alias).filter(code='USD').delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcurrency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RunPython(_build_usd, _destroy_usd),
    ]
