# Generated by Django 2.2 on 2019-04-26 15:52

from django.db import migrations, models
import django.db.models.deletion
import findance.abstract


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwningEntity',
            fields=[
                ('id', findance.abstract.FindanceIdField(default=findance.abstract.FindanceIdField._build_id, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('assets', models.ManyToManyField(through='assets.AssetOwnership', to='assets.Asset')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityControl',
            fields=[
                ('id', findance.abstract.FindanceIdField(default=findance.abstract.FindanceIdField._build_id, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('o', 'Read Owned'), ('r', 'Read All'), ('w', 'Write'), ('a', 'Admin')], default='r', max_length=1)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.OwningEntity')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
